CREATE DATABASE "mtop" WITH ENCODING = 'UTF-8';

\c "mtop";

CREATE TABLE "mtop_user"(
    "username" VARCHAR(128) NOT NULL PRIMARY KEY,
    "salt" VARCHAR(32) NOT NULL,
    "password" VARCHAR(1024) NOT NULL DEFAULT '',
    "created_time" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    "updated_time" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
